version: '3.4'

services:

  dockercrud:
    image: ${DOCKER_REGISTRY-}dockersqlasp
    build:
      context: .
      dockerfile: DockerCrud/Dockerfile

  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=1Secure*Password1
      - ACCEPT_EULA=Y
    ports:
      - "1440:1433"